spring:
  application:
    name: GestaoDeTarefas

  datasource:
    url: jdbc:h2:mem:tarefasdb
    driverClassName: org.h2.Driver
    username: sa
    password: ""

  # jpa:
  #   database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always
