spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create

server:
  port: ${PORT:8080}

